import type { LanguageMessages } from "../src/types.ts";

export default {
  "zh-CN": {
    Home: "首页",
    Guide: "指南",
    "Quick Start": "快速开始",
    Layout: "布局",
    Components: "组件",
    "Components List": "组件列表",
    Documentation: "文档中心",
    Contributors: "贡献者",
    sidebar: {
      homeLayout: "首页布局",
      config: "配置",
      runtime: "运行时",
      inlineScript: "内联脚本",
      footerScript: "页脚脚本",
      highlight: "代码高亮",
      locale: "国际化",
      menu: "菜单",
      sidebar: "侧边栏",
      toc: "目录",
      prevNext: "分页导航",
      sitemap: "站点地图",
      robots: "Robots",
      llms: "LLMs",
      externalLink: "外部链接",
      others: "其他",
      changelog: "变更日志",
    },
    mobile: {
      navigation: "导航",
      toc: "目录",
    },
    search: {
      button: "搜索",
      title: "搜索文档",
      placeholder: "输入关键词...",
      empty: "没有找到匹配内容",
      hint: "输入关键词搜索标题和正文",
    },
    prevNext: {
      previous: "上一页",
      next: "下一页",
    },
    theme: {
      button: "主题",
    },
    auth: {
      login: "登录",
    },
  },
  en: {
    sidebar: {
      homeLayout: "Home Layout",
      config: "Config",
      runtime: "Runtime",
      inlineScript: "Inline Script",
      footerScript: "Footer Script",
      highlight: "Highlight",
      locale: "Locale",
      menu: "Menu",
      sidebar: "Sidebar",
      toc: "Contents",
      prevNext: "Prev/Next",
      sitemap: "Sitemap",
      robots: "Robots",
      llms: "LLMs",
      quickStart: "Quick Start",
      layout: "Layout",
      externalLink: "External Link",
      others: "Others",
      changelog: "Changelog",
    },
    mobile: {
      navigation: "Navigation",
      toc: "Contents",
    },
    search: {
      button: "Search",
      title: "Search Docs",
      placeholder: "Type keywords...",
      empty: "No results found",
      hint: "Search titles and page content",
    },
    prevNext: {
      previous: "Previous",
      next: "Next",
    },
    theme: {
      button: "Theme",
    },
    auth: {
      login: "Login",
    },
  },
} satisfies LanguageMessages;
